# Generated by Django 4.0.1 on 2022-03-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_feedback_namam_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
