# Generated by Django 4.0.1 on 2022-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_member_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Ph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
